<?php


/*
 * Copyright (C) 2016 polux
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

namespace MyGED\Testing\Application;

use MyGED\Application\App as App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-18 at 17:00:47.
 */
class AppTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        App::setAppParam('SQLITE_DB_FILEPATH', '/home/polux/Projects/php-myged/data/app.db');
        App::setAppParam('MODE', 'DEBUG');
        App::setAppParam('VAULT_ROOT', '/home/polux/Projects/php-myged/tests/phpunit/vault-tests/vault-tmp');
        App::setAppParam('VAULT_DB', '/home/polux/Projects/php-myged/tests/phpunit/vault-tests/vault-tmp/db/vault.db');
        App::setAppParam('TEMPLATES_ROOT', '/home/polux/Projects/php-myged/application/templates');
        
        // Database init...
        App::initDatabase();
        
        // Vault init...
        App::initVault(true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * testGetMetadataAppDabaseObject
     * 
     * @covers MyGED\Core\Application\App::getMetadataAppDabaseObject
     */
    public function testGetMetadataAppDabaseObject()
    {
        $this->assertTrue(App::getAppDabaseObject() instanceof \PDO);
    }

    /**
     * @covers MyGED\Core\Application\App::getAppParam
     * @test
     */
    public function testGetAppParam()
    {
        // Remove the following lines when you implement this test.
        $this->assertEquals(App::getAppParam('SQLITE_DB_FILEPATH'), '/home/polux/Projects/php-myged/data/app.db');
    }

    /**
     * @covers MyGED\Core\Application\App::setAppParam
     * @test
     */
    public function testSetAppParam()
    {
        $this->assertEquals(App::getAppParam('SQLITE_DB_FILEPATH'), '/home/polux/Projects/php-myged/data/app.db');
    }
}
